### ISSUE TITLE
Erro no Magento 2.4.5 (PHP 8.1.22 )

### ISSUE THREAD

**Issue by lucasCarvalhaes** [r-martins/PagBank-Magento2#4]
Erro na compilação do magento:

Compilation was started.
Interceptors generation... 4/9 [============>---------------]  44% 12 secs 288.0 MiBCall to undefined method ReflectionUnionType::getName()#0 /var/www/html/magento2/vendor/magento/framework/Interception/Code/Generator/Interceptor.php(105): Magento\Framework\Interception\Code\Generator\Interceptor->getReturnTypeValue()
#1 /var/www/html/magento2/vendor/magento/framework/Interception/Code/Generator/Interceptor.php(76): Magento\Framework\Interception\Code\Generator\Interceptor->_getMethodInfo()
#2 /var/www/html/magento2/vendor/magento/framework/Code/Generator/EntityAbstract.php(228): Magento\Framework\Interception\Code\Generator\Interceptor->_getClassMethods()
#3 /var/www/html/magento2/vendor/magento/framework/Interception/Code/Generator/Interceptor.php(177): Magento\Framework\Code\Generator\EntityAbstract->_generateCode()
#4 /var/www/html/magento2/vendor/magento/framework/Code/Generator/EntityAbstract.php(108): Magento\Framework\Interception\Code\Generator\Interceptor->_generateCode()
#5 /var/www/html/magento2/vendor/magento/framework/Code/Generator.php(130): Magento\Framework\Code\Generator\EntityAbstract->generate()
#6 /var/www/html/magento2/setup/src/Magento/Setup/Module/Di/Code/Generator.php(69): Magento\Framework\Code\Generator->generateClass()
#7 /var/www/html/magento2/setup/src/Magento/Setup/Module/Di/App/Task/Operation/Interception.php(100): Magento\Setup\Module\Di\Code\Generator->generateList()
#8 /var/www/html/magento2/setup/src/Magento/Setup/Module/Di/App/Task/Manager.php(56): Magento\Setup\Module\Di\App\Task\Operation\Interception->doOperation()
#9 /var/www/html/magento2/setup/src/Magento/Setup/Console/Command/DiCompileCommand.php(216): Magento\Setup\Module\Di\App\Task\Manager->process()
#10 /var/www/html/magento2/vendor/symfony/console/Command/Command.php(255): Magento\Setup\Console\Command\DiCompileCommand->execute()
#11 /var/www/html/magento2/vendor/symfony/console/Application.php(1021): Symfony\Component\Console\Command\Command->run()
#12 /var/www/html/magento2/vendor/symfony/console/Application.php(275): Symfony\Component\Console\Application->doRunCommand()
#13 /var/www/html/magento2/vendor/magento/framework/Console/Cli.php(116): Symfony\Component\Console\Application->doRun()
#14 /var/www/html/magento2/vendor/symfony/console/Application.php(149): Magento\Framework\Console\Cli->doRun()
#15 /var/www/html/magento2/bin/magento(23): Symfony\Component\Console\Application->run()
#16 {main}

**Comment by r-martins** [comment]
Oi, @lucasCarvalhaes . Td bom?
O que o fez concluir que é um problema no módulo de pagamento? Não vejo ele em lugar algum do backtrace dessa compilação, e compilação faz parte dos testes automatizados quando lançamos no mktplace (ou seja, se tivesse bug aí ele não seria publicado lá).

Além disso, o erro de compilação que você está enfrentando pode não estar diretamente relacionado ao módulo PagBank, mas sim a um problema de compatibilidade entre o Magento e o PHP 8.0. Talvez você esteja rodando um php < 8.0 na hora da compilação.

Esperimente rodar `php -v` no terminal pra ter certeza.
